#!/bin/bash
#-------------------------------------------------
NPROCS=`cat system/decomposeParDict | grep "numberOfSub" | awk '{print $2}' | sed -e 's/;//g'`

echo "Number of processors :"$NPROCS

mpirun -np $NPROCS pemfcFoam -parallel >& pemfcFoam.parallel.log
